# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

repos_owner = "goldeneggg"
repos_name = "provisioning-scripts"
pf = "centos7"
scripts = ["cui.sh", "docker.sh"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos70_x86"
  config.vm.box_url = "https://f0fff3908f081cb6461b407be80daf97f07ac418.googledrive.com/host/0BwtuV7VyVTSkUG1PM3pCeDJ4dVE/centos7.box"

  config.vm.define :vmcentos7 do |vmcentos7|
    vmcentos7.vm.hostname = "vmcentos7"

    vmcentos7.vm.network :private_network, ip: "192.168.56.101"

    vmcentos7.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 1024]
    end

    # port forward for docker remote api
    forward_ports = { 2375 => 2375 }
    forward_ports.each do |host_port, guest_port|
      vmcentos7.vm.network :forwarded_port, host: host_port, guest: guest_port
    end

    # provisioning
    scripts.each do |sc|
      vmcentos7.vm.provision :shell, path: "https://raw.githubusercontent.com/#{repos_owner}/#{repos_name}/master/facade.sh", args: [pf, sc]
    end
  end
end
